### ISSUE TITLE
TypeError: Cannot read property 'send' of undefined

### ISSUE THREAD

**Issue by SuNG0D** [atachh/discord-spam-bot#3]
Here's the error text:

TypeError: Cannot read property 'send' of undefined
    at Timeout.setInterval [as _onTimeout] (/home/kali/Desktop/discord-spam-bot-master/index.js:76:29)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)

**Comment by patelom693** [comment]
Same here
